name = "Jade ğŸ”"
filename = "Jade-1.18-4.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/113/Jade-1.18-4.1.1.jar"
hash-format = "murmur2"
hash = "1159267320"

[update]
[update.curseforge]
file-id = 3597113
project-id = 324717
