name = "Jade ğŸ”"
filename = "Jade-1.18-4.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/180/Jade-1.18-4.1.2.jar"
hash-format = "murmur2"
hash = "3133870803"

[update]
[update.curseforge]
file-id = 3614180
project-id = 324717
